model_checkpoint: "t5-small"

data:
  dataset_name: "cnn_dailymail"
  dataset_config: "3.0.0"

save_dir: "models/t5-cnn-dailymail"

use_subset: true
subset_train_size: 50000
subset_val_size: 5000

preprocessing:
  max_input_length: 256
  max_target_length: 64
  num_proc: 6

training:
  train_batch_size: 4
  eval_batch_size: 4
  num_train_epochs: 2
  learning_rate: 3e-4
  logging_steps: 100
  gradient_accumulation_steps: 1
  warmup_steps: 500
  resume_from_checkpoint: true
  save_total_limit: 2
  eval_strategy: "epoch"
  save_strategy: "epoch"
